#Prefix
unbind C-b
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Mouse
set -g mouse on

# Reload Config
bind R source-file ~/.config/tmux/tmux.conf

# Default Terminal
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
